config/routes.rb
Movieslist::Application.routes.draw do
  root 'static_pages#home'

  match '/register',  to: 'users#new',            via: 'get'
  match '/login',     to: 'sessions#new',         via: 'get'
  match '/logout',    to: 'sessions#destroy',     via: 'delete'
  match '/about',     to: 'static_pages#about',   via: 'get'
  match '/help',      to: 'static_pages#help',    via: 'get'
  match '/kittens',   to: 'static_pages#kittens', via: 'get'
  match '/contact',   to: 'static_pages#contact', via: 'get'
  match '/blog',      to: 'blogposts#index',      via: 'get'

  resources :sessions, only: [:new, :create, :destroy]
  resources :users  
  resources :blogposts
  resources :blogcomments, only: [:create, :destroy]
  resources :movies

end

app/models/blogpost.rb
class Blogpost < ActiveRecord::Base
	has_many :blogcomments, dependent: :destroy
	belongs_to :user
	default_scope -> { order('created_at DESC') }
	validates :user_id, presence: true
	validates :title,   presence: true
end

app/controllers/blogposts_controller.rb
class BlogpostsController < ApplicationController
  before_action :admin_user, only: [:new, :create, :edit, :update, :destroy]

  def index
  	@blogposts = Blogpost.paginate(page: params[:page], per_page: 5)
  end

  def show
  	@blogpost = Blogpost.find(params[:id])
    @blogcomment = @blogpost.blogcomments.build 
    @blogcomments = @blogpost.blogcomments.paginate(page: params[:page])
  end

  def new
  	@blogpost = Blogpost.new
  end

  def create
  	@blogpost = current_user.blogposts.build(blogpost_params)
    if @blogpost.save
      flash[:success] = "Blog post created!"
      redirect_to blog_url
    else
      render 'new'
    end
  end

  def edit
    @blogpost = Blogpost.find(params[:id])
  end

  def update
    @blogpost = Blogpost.find(params[:id])
    if @blogpost.update_attributes(blogpost_params)
      flash[:success] = "Blog post updated!"
      redirect_to blogpost_url
    else
      render 'edit'
    end
  end

  def destroy
    Blogpost.find(params[:id]).destroy
    flash[:success] = "Blog post deleted successfully."
    redirect_to blog_url
  end

  private
  def blogpost_params
  	params.require(:blogpost).permit(:title, :content)  	
  end
end

app/helpers/blogposts_helper.rb
module BlogpostsHelper
end

app/views/blogposts/_blogpost.html.erb
<div class="blogpost">
	 <h2><%= link_to blogpost.title, blogpost %> </h2>
	 <span class="timestamp">Posted <%= time_ago_in_words(blogpost.created_at) %> ago by: <%= link_to blogpost.user.name, blogpost.user %> </span>
	 <% if admin_user? %>
	 	<div class="pull-right">
		 <%= link_to "Edit", edit_blogpost_path(blogpost), :class => "btn btn-default" %>
		 <%= link_to "Delete", blogpost, :class => "btn btn-danger", method: :delete, data:{ confirm: "Are you sure you want to delete this beautiful post?" } %>
		</div>
	 <% end %>
	 <div class="post">
	 	<%= simple_format blogpost.content %> 
	 </div>
	 <% if blogpost.created_at != blogpost.updated_at %>
	 	<span class="timestamp">Updated <%= time_ago_in_words(blogpost.updated_at) %> ago.</span>
	 <% end %>
</div>

app/views/blogposts/edit.html.erb
<% provide(:title, 'Edit blog post') %>
<h1>Edit Blog Post</h1>
<div class="row">
  <div class="span6 offset3">
  	<%= form_for @blogpost do |f| %>
      <%= render 'shared/error_messages', object: f.object %>
      
  		<%= f.label :title %>
  		<%= f.text_field :title %>

  		<%= f.label :content %>
  		<%= f.text_area :content %>

  		<%= f.submit "Submit post" , class: "btn btn-large btn-primary" %>
  	<% end %>
  </div>
</div>

app/views/blogposts/index.html.erb
<% provide(:title, 'Blog') %>
<h1>AGNI KAI Blog</h1>

<%= will_paginate %>

<div class="blogposts">
	<%= link_to 'New post', new_blogpost_path, :class => "btn btn-inverse" if admin_user?%>
	  <%= render @blogposts %>
</div>

<%= will_paginate %>

app/views/blogposts/new.html.erb
<% provide(:title, 'New blog post') %>
<h1>New Blog Post</h1>

<div class="row">
  <div class="span8 offset2">
  	<%= form_for(@blogpost) do |f| %>
      <%= render 'shared/error_messages', object: f.object %>
      
  		<%= f.label :title %>
  		<%= f.text_field :title %>

  		<%= f.label :content %>
  		<%= f.text_area :content %>

  		<%= f.submit "Submit post" , class: "btn btn-large btn-primary" %>
  	<% end %>
  </div>
</div>

app/views/blogposts/show.html.erb
<% provide(:title, @blogpost.title) %>
<%= render @blogpost %>
<div>
	<h3>Comment section (<%= @blogpost.blogcomments.count %>)</h3>
	<% unless logged_in? %>
		<div class="alert"> 
			Please log in if you'd like to comment.
		</div>
	<% end %>
	<%= render 'shared/blogcomment_form' %>
	<% if @blogpost.blogcomments.any? %>
		<ul class="media-list">
			<%= render @blogcomments %>
		</ul>
		<%= will_paginate @blogcomments %>
	<% end %>
</div>