config/routes.rb
Movieslist::Application.routes.draw do
  root 'static_pages#home'

  match '/register',  to: 'users#new',            via: 'get'
  match '/login',     to: 'sessions#new',         via: 'get'
  match '/logout',    to: 'sessions#destroy',     via: 'delete'
  match '/about',     to: 'static_pages#about',   via: 'get'
  match '/help',      to: 'static_pages#help',    via: 'get'
  match '/kittens',   to: 'static_pages#kittens', via: 'get'
  match '/contact',   to: 'static_pages#contact', via: 'get'
  match '/blog',      to: 'blogposts#index',      via: 'get'

  resources :sessions, only: [:new, :create, :destroy]
  resources :users  
  resources :blogposts
  resources :blogcomments, only: [:create, :destroy]
  resources :movies

end

app/views/layouts/_footer.erb
  <footer>
    <small>
      AGNI KAI&copy; by L & A 2014
    </small>
    <span class="pull-right"> <%= image_tag("kittens.png", alt: "Cats.") %></span>
    <div class="btn-group">
      <%= link_to "About", about_path, :class => "btn btn-default" %>
      <%= link_to "Help", help_path, :class => "btn btn-default" %>
      <%= link_to "Contact", contact_path, :class => "btn btn-default" %>
    </div>
  </footer>

app/views/layouts/_header.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="navbar-inner">
   <div class="container">
   <%= link_to "AGNI KAI", root_path, :class => "brand" %>
   <nav>
     <ul class="nav">
      <li> <%= link_to "Home", root_path %> </li>
      <li> <%= link_to "Blog", blog_path %> </li>
      <li> <%= link_to "Kittens", kittens_path %> </li>
      <li> <%= link_to "Users", users_path %></li>
      <li> <%= link_to "Movies", movies_path %></li>
    </ul>
    <ul class ="nav pull-right">
     <% if logged_in? %>
       <li id="fat-menu" class="dropdown">
         <a href="#" class="dropdown-toggle" data-toggle="dropdown">
          Account <b class="caret"></b>
         </a>
         <ul class="dropdown-menu">
          <li><%= link_to "Profile", current_user %></li>
          <li><%= link_to "Settings", edit_user_path(current_user) %></li>
          <li class="divider"></li>
          <li>
            <%= link_to "Logout", logout_path, method: "delete" %>
          </li>
       </ul>
     </li>
   <% else %>
   <%= link_to "Login", login_path, :class => "btn btn-primary" %>
   <% end %>
 </ul>
</nav><!--/.nav-collapse -->
</div><!-- / container -->
</div> <!-- / navbar-inner -->
</header>

app/views/layouts/_shim.html.erb
    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

    <%= javascript_include_tag "application" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>AGNI KAI | <%= content_for?(:title) ? yield(:title) : "" %></title>
    <%= csrf_meta_tags %>
    <%= render 'layouts/shim' %>
    <%= render 'layouts/header' %>
  </head>
  <body>
   <div class="container">
    <%= bootstrap_flash %>
    <div class="hero-unit">
     <%= yield %>
    </div>    <%= render 'layouts/footer' %> 
    <%= debug(params) if Rails.env.development? %>   
  </div> <!-- /container -->
  </body>
</html>